# Pre-commit hooks for MCP Todo Server
# Install with: pre-commit install

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: go-imports
      - id: go-cyclo
        args: [-over=15]
      - id: go-mod-tidy
      - id: go-unit-tests
      - id: golangci-lint

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: local
    hooks:
      - id: no-direct-todo-file-manipulation
        name: Check for direct todo file manipulation
        entry: "Edit.*\\.claude/todos/|Write.*\\.claude/todos/"
        language: pygrep
        types: [go]
        exclude: ^(test_|.*_test\.go)
        
      - id: make-test
        name: Run tests
        entry: make test-short
        language: system
        pass_filenames: false
        always_run: true