version: '3.8'

services:
  mcp-todo-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-todo-server
    ports:
      - "8080:8080"
    environment:
      - MCP_TRANSPORT=http
      - MCP_PORT=8080
      - MCP_HOST=0.0.0.0
      - LOG_LEVEL=info
    volumes:
      # Mount host's Claude todo directory
      - ~/.claude/todos:/home/mcp/.claude/todos
    restart: unless-stopped
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  mcp-network:
    driver: bridge